import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import HeaderSection from './components/Common/HeaderSection'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  //file for defining common layout for pages
  return (
    <html lang="en" data-theme="winter">
      <body className={inter.className}>
        <HeaderSection />
        {children}
      </body>
    </html>
  )
}
